language: c
os:
  - linux
  # - osx

env:
  global:
    - GOPATH=~
    - DOTPATH=~/dotfiles

install:
  - curl -L raw.githubusercontent.com/orihuzak/dotfiles/master/etc/install.sh | bash

# before_script:
#   - cd $DOTPATH

# script:
#   - make deploy
#   - make init
  # - make --silent test

