language: c
os:
  - linux
  - osx

env:
  global:
    - DOTPATH=~/.dotfiles
    - GOPATH=~

install:
  - curl -L https://raw.githubusercontent.com/orihuzak/dotfiles/master/etc/install.sh | bash

# before_script:
#   - cd $(DOTPATH)

# script:
#   - make init
  # - make --silent test

